name = "PEPSTutorial"
uuid = "bb9fc252-1490-444b-abb1-8cbb908c33a9"
version = "0.1.0"
authors = ["Lukas Devos <ldevos98@gmail.com>"]

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoTeachingTools = "661c6b06-c737-4d37-b85c-46df65de6f69"

[compat]
Pluto = "0.20.21"
PlutoTeachingTools = "0.4.6"
